<a href="https://colab.research.google.com/github/ElsCorporation/ChallengeAluraTelecomPt2/blob/main/Callenge_Alura_TelecomX_pt2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd

# Extração do Arquivo Tratado

In [2]:
url = 'https://raw.githubusercontent.com/ElsCorporation/ChallengeAluraTelecomPt2/refs/heads/main/dados_telecom_x.csv'
dados = pd.read_csv(url)
dados.head()

,cliente_ID,Churn,cliente_genero,cliente_senior,cliente_parceiro,cliente_dependentes,cliente_tenure,telefone_servico,telefone_multiplas_linhas,internet_servico,...,internet_protecao_dispositivo,internet_suporte_tecnico,internet_streaming_tv,internet_streaming_filmes,conta_contrato,conta_fatura_online,conta_metodo_pagamento,conta_mensal,conta_total,Contas_Diarias
0,0002-ORFBO,No,Feminino,0,1,1,9,1,0,DSL,...,0,1,1,0,One year,1,Mailed check,65.6,593.30,2.20
1,0003-MKNFE,No,Masculino,0,0,0,9,1,1,DSL,...,0,0,0,1,Month-to-month,0,Mailed check,59.9,542.40,2.01
2,0004-TLHLJ,Yes,Masculino,0,0,0,4,1,0,Fiber optic,...,1,0,0,0,Month-to-month,1,Electronic check,73.9,280.85,2.34
3,0011-IGKFF,Yes,Masculino,1,1,0,13,1,0,Fiber optic,...,1,0,1,1,Month-to-month,1,Electronic check,98.0,1237.85,3.17
4,0013-EXCHZ,Yes,Feminino,1,1,0,3,1,0,Fiber optic,...,0,1,1,0,Month-to-month,1,Mailed check,83.9,267.40,2.97

# Remoção de Colunas Irrelevantes

---

In [3]:
dados.columns

Index(['cliente_ID', 'Churn', 'cliente_genero', 'cliente_senior',
       'cliente_parceiro', 'cliente_dependentes', 'cliente_tenure',
       'telefone_servico', 'telefone_multiplas_linhas', 'internet_servico',
       'internet_seguranca_online', 'internet_backup_online',
       'internet_protecao_dispositivo', 'internet_suporte_tecnico',
       'internet_streaming_tv', 'internet_streaming_filmes', 'conta_contrato',
       'conta_fatura_online', 'conta_metodo_pagamento', 'conta_mensal',
       'conta_total', 'Contas_Diarias'],
      dtype='object')

In [4]:
dados.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7043 entries, 0 to 7042
Data columns (total 22 columns):
 #   Column                         Non-Null Count  Dtype
---  ------                         --------------  -----
 0   cliente_ID                     7043 non-null   object
 1   Churn                          7043 non-null   object
 2   cliente_genero                 7043 non-null   object
 3   cliente_senior                 7043 non-null   int64
 4   cliente_parceiro               7043 non-null   int64
 5   cliente_dependentes            7043 non-null   int64
 6   cliente_tenure                 7043 non-null   int64
 7   telefone_servico               7043 non-null   int64
 8   telefone_multiplas_linhas      7043 non-null   object
 9   internet_servico               7043 non-null   object
 10  internet_seguranca_online      7043 non-null   object
 11  internet_backup_online         7043 non-null   object
 12  internet_protecao_dispositivo  7043 non-null   object
 13  internet_suporte_tecnico       7043 non-null   object
 14  internet_streaming_tv          7043 non-null   object
 15  internet_streaming_filmes      7043 non-null   object
 16  conta_contrato                 7043 non-null   object
 17  conta_fatura_online            7043 non-null   int64
 18  conta_metodo_pagamento         7043 non-null   object
 19  conta_mensal                   7043 non-null   float64
 20  conta_total                    7032 non-null   float64
 21  Contas_Diarias                 7032 non-null   float64
dtypes: float64(3), int64(6), object(13)
memory usage: 1.2+ MB

In [5]:
dados['internet_servico'].nunique()

3

In [6]:
colunas_remocao = {
    'cliente_ID',
    'cliente_genero',
    'telefone_multiplas_linhas',
    'internet_streaming_tv',
    'internet_streaming_filmes',
    'conta_mensal',
    'Contas_Diarias'
}

In [23]:
dados_colunas_removidas = dados.drop(columns=colunas_remocao, axis=1)
dados_colunas_removidas.head()

,Churn,cliente_senior,cliente_parceiro,cliente_dependentes,cliente_tenure,telefone_servico,internet_servico,internet_seguranca_online,internet_backup_online,internet_protecao_dispositivo,internet_suporte_tecnico,conta_contrato,conta_fatura_online,conta_metodo_pagamento,conta_total
0,No,0,1,1,9,1,DSL,0,1,0,1,One year,1,Mailed check,593.30
1,No,0,0,0,9,1,DSL,0,0,0,0,Month-to-month,0,Mailed check,542.40
2,Yes,0,0,0,4,1,Fiber optic,0,0,1,0,Month-to-month,1,Electronic check,280.85
3,Yes,1,1,0,13,1,Fiber optic,0,1,1,0,Month-to-month,1,Electronic check,1237.85
4,Yes,1,1,0,3,1,Fiber optic,0,0,0,1,Month-to-month,1,Mailed check,267.40

In [8]:
dados_colunas_removidas.columns

Index(['Churn', 'cliente_senior', 'cliente_parceiro', 'cliente_dependentes',
       'cliente_tenure', 'telefone_servico', 'internet_servico',
       'internet_seguranca_online', 'internet_backup_online',
       'internet_protecao_dispositivo', 'internet_suporte_tecnico',
       'conta_contrato', 'conta_fatura_online', 'conta_metodo_pagamento',
       'conta_total'],
      dtype='object')

In [24]:
Adicionar_colunas_streaming = [
    'internet_streaming_tv',
    'internet_streaming_filmes',
]
dados_colunas_removidas = pd.concat([dados_colunas_removidas, dados[Adicionar_colunas_streaming]], axis=1)
dados_colunas_removidas.head()

,Churn,cliente_senior,cliente_parceiro,cliente_dependentes,cliente_tenure,telefone_servico,internet_servico,internet_seguranca_online,internet_backup_online,internet_protecao_dispositivo,internet_suporte_tecnico,conta_contrato,conta_fatura_online,conta_metodo_pagamento,conta_total,internet_streaming_tv,internet_streaming_filmes
0,No,0,1,1,9,1,DSL,0,1,0,1,One year,1,Mailed check,593.30,1,0
1,No,0,0,0,9,1,DSL,0,0,0,0,Month-to-month,0,Mailed check,542.40,0,1
2,Yes,0,0,0,4,1,Fiber optic,0,0,1,0,Month-to-month,1,Electronic check,280.85,0,0
3,Yes,1,1,0,13,1,Fiber optic,0,1,1,0,Month-to-month,1,Electronic check,1237.85,1,1
4,Yes,1,1,0,3,1,Fiber optic,0,0,0,1,Month-to-month,1,Mailed check,267.40,1,0

In [25]:
dados_colunas_removidas['internet_streaming_tv'].unique()

array(['1', '0', 'No internet service'], dtype=object)

In [26]:
dados_colunas_removidas.columns

Index(['Churn', 'cliente_senior', 'cliente_parceiro', 'cliente_dependentes',
       'cliente_tenure', 'telefone_servico', 'internet_servico',
       'internet_seguranca_online', 'internet_backup_online',
       'internet_protecao_dispositivo', 'internet_suporte_tecnico',
       'conta_contrato', 'conta_fatura_online', 'conta_metodo_pagamento',
       'conta_total', 'internet_streaming_tv', 'internet_streaming_filmes'],
      dtype='object')

In [30]:
AjusteColunas = [
    'internet_seguranca_online',
    'internet_backup_online',
    'internet_protecao_dispositivo',
    'internet_suporte_tecnico',
    'internet_streaming_tv',
    'internet_streaming_filmes',
]

for col in AjusteColunas:
    dados_colunas_removidas[col] = dados_colunas_removidas[col].replace(0, '0')

dados_colunas_removidas['internet_streaming_tv'].unique()

array(['1', '0'], dtype=object)

In [31]:
dados_colunas_removidas.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7043 entries, 0 to 7042
Data columns (total 17 columns):
 #   Column                         Non-Null Count  Dtype
---  ------                         --------------  -----
 0   Churn                          7043 non-null   object
 1   cliente_senior                 7043 non-null   int64
 2   cliente_parceiro               7043 non-null   int64
 3   cliente_dependentes            7043 non-null   int64
 4   cliente_tenure                 7043 non-null   int64
 5   telefone_servico               7043 non-null   int64
 6   internet_servico               7043 non-null   object
 7   internet_seguranca_online      7043 non-null   object
 8   internet_backup_online         7043 non-null   object
 9   internet_protecao_dispositivo  7043 non-null   object
 10  internet_suporte_tecnico       7043 non-null   object
 11  conta_contrato                 7043 non-null   object
 12  conta_fatura_online            7043 non-null   int64
 13  conta_metodo_pagamento         7043 non-null   object
 14  conta_total                    7032 non-null   float64
 15  internet_streaming_tv          7043 non-null   object
 16  internet_streaming_filmes      7043 non-null   object
dtypes: float64(1), int64(6), object(10)
memory usage: 935.5+ KB

In [32]:
AjusteColunasAstype = [
    'internet_seguranca_online',
    'internet_backup_online',
    'internet_protecao_dispositivo',
    'internet_suporte_tecnico',
    'internet_streaming_tv',
    'internet_streaming_filmes',
]

for col in AjusteColunasAstype:
    dados_colunas_removidas[col] = dados_colunas_removidas[col].astype(int)

dados_colunas_removidas.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7043 entries, 0 to 7042
Data columns (total 17 columns):
 #   Column                         Non-Null Count  Dtype
---  ------                         --------------  -----
 0   Churn                          7043 non-null   object
 1   cliente_senior                 7043 non-null   int64
 2   cliente_parceiro               7043 non-null   int64
 3   cliente_dependentes            7043 non-null   int64
 4   cliente_tenure                 7043 non-null   int64
 5   telefone_servico               7043 non-null   int64
 6   internet_servico               7043 non-null   object
 7   internet_seguranca_online      7043 non-null   int64
 8   internet_backup_online         7043 non-null   int64
 9   internet_protecao_dispositivo  7043 non-null   int64
 10  internet_suporte_tecnico       7043 non-null   int64
 11  conta_contrato                 7043 non-null   object
 12  conta_fatura_online            7043 non-null   int64
 13  conta_metodo_pagamento         7043 non-null   object
 14  conta_total                    7032 non-null   float64
 15  internet_streaming_tv          7043 non-null   int64
 16  internet_streaming_filmes      7043 non-null   int64
dtypes: float64(1), int64(12), object(4)
memory usage: 935.5+ KB

In [33]:
dados_colunas_removidas['Churn'].unique()

array(['No', 'Yes'], dtype=object)

In [35]:
dados_colunas_removidas['Churn'] = dados_colunas_removidas['Churn'].replace({'No': 0, 'Yes': 1}).astype(int)
dados_colunas_removidas['Churn']

/tmp/ipython-input-3885971513.py:1: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  dados_colunas_removidas['Churn'] = dados_colunas_removidas['Churn'].replace({'No': 0, 'Yes': 1}).astype(int)

0       0
1       0
2       1
3       1
4       1
       ..
7038    0
7039    1
7040    0
7041    0
7042    0
Name: Churn, Length: 7043, dtype: int64

In [36]:
dados_colunas_removidas.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7043 entries, 0 to 7042
Data columns (total 17 columns):
 #   Column                         Non-Null Count  Dtype
---  ------                         --------------  -----
 0   Churn                          7043 non-null   int64
 1   cliente_senior                 7043 non-null   int64
 2   cliente_parceiro               7043 non-null   int64
 3   cliente_dependentes            7043 non-null   int64
 4   cliente_tenure                 7043 non-null   int64
 5   telefone_servico               7043 non-null   int64
 6   internet_servico               7043 non-null   object
 7   internet_seguranca_online      7043 non-null   int64
 8   internet_backup_online         7043 non-null   int64
 9   internet_protecao_dispositivo  7043 non-null   int64
 10  internet_suporte_tecnico       7043 non-null   int64
 11  conta_contrato                 7043 non-null   object
 12  conta_fatura_online            7043 non-null   int64
 13  conta_metodo_pagamento         7043 non-null   object
 14  conta_total                    7032 non-null   float64
 15  internet_streaming_tv          7043 non-null   int64
 16  internet_streaming_filmes      7043 non-null   int64
dtypes: float64(1), int64(13), object(3)
memory usage: 935.5+ KB

In [38]:
dados_colunas_removidas = pd.concat([dados_colunas_removidas, dados['cliente_genero']], axis=1)
dados_colunas_removidas['cliente_genero']

0        Feminino
1       Masculino
2       Masculino
3       Masculino
4        Feminino
          ...
7038     Feminino
7039    Masculino
7040    Masculino
7041    Masculino
7042    Masculino
Name: cliente_genero, Length: 7043, dtype: object

# Encoding

In [39]:
dados_colunas_removidas.columns

Index(['Churn', 'cliente_senior', 'cliente_parceiro', 'cliente_dependentes',
       'cliente_tenure', 'telefone_servico', 'internet_servico',
       'internet_seguranca_online', 'internet_backup_online',
       'internet_protecao_dispositivo', 'internet_suporte_tecnico',
       'conta_contrato', 'conta_fatura_online', 'conta_metodo_pagamento',
       'conta_total', 'internet_streaming_tv', 'internet_streaming_filmes',
       'cliente_genero'],
      dtype='object')

In [46]:
colunas_categoricas = [
        'Churn', 'cliente_senior', 'cliente_parceiro', 'cliente_dependentes',
        'telefone_servico', 'internet_servico',
       'internet_seguranca_online', 'internet_backup_online',
       'internet_protecao_dispositivo', 'internet_suporte_tecnico',
       'conta_contrato', 'conta_fatura_online', 'conta_metodo_pagamento',
      'internet_streaming_tv', 'internet_streaming_filmes',
       'cliente_genero'
]

In [47]:
dados_encoded = pd.get_dummies(dados_colunas_removidas, columns=colunas_categoricas, drop_first = True)
dados_encoded.head()

,cliente_tenure,conta_total,Churn_1,cliente_senior_1,cliente_parceiro_1,cliente_dependentes_1,telefone_servico_1,internet_servico_Fiber optic,internet_servico_No,internet_seguranca_online_1,...,internet_suporte_tecnico_1,conta_contrato_One year,conta_contrato_Two year,conta_fatura_online_1,conta_metodo_pagamento_Credit card (automatic),conta_metodo_pagamento_Electronic check,conta_metodo_pagamento_Mailed check,internet_streaming_tv_1,internet_streaming_filmes_1,cliente_genero_Masculino
0,9,593.30,False,False,True,True,True,False,False,False,...,True,True,False,True,False,False,True,True,False,False
1,9,542.40,False,False,False,False,True,False,False,False,...,False,False,False,False,False,False,True,False,True,True
2,4,280.85,True,False,False,False,True,True,False,False,...,False,False,False,True,False,True,False,False,False,True
3,13,1237.85,True,True,True,False,True,True,False,False,...,False,False,False,True,False,True,False,True,True,True
4,3,267.40,True,True,True,False,True,True,False,False,...,True,False,False,True,False,False,True,True,False,False

In [48]:
dados_encoded.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7043 entries, 0 to 7042
Data columns (total 22 columns):
 #   Column                                          Non-Null Count  Dtype
---  ------                                          --------------  -----
 0   cliente_tenure                                  7043 non-null   int64
 1   conta_total                                     7032 non-null   float64
 2   Churn_1                                         7043 non-null   bool
 3   cliente_senior_1                                7043 non-null   bool
 4   cliente_parceiro_1                              7043 non-null   bool
 5   cliente_dependentes_1                           7043 non-null   bool
 6   telefone_servico_1                              7043 non-null   bool
 7   internet_servico_Fiber optic                    7043 non-null   bool
 8   internet_servico_No                             7043 non-null   bool
 9   internet_seguranca_online_1                     7043 non-null   bool
 10  internet_backup_online_1                        7043 non-null   bool
 11  internet_protecao_dispositivo_1                 7043 non-null   bool
 12  internet_suporte_tecnico_1                      7043 non-null   bool
 13  conta_contrato_One year                         7043 non-null   bool
 14  conta_contrato_Two year                         7043 non-null   bool
 15  conta_fatura_online_1                           7043 non-null   bool
 16  conta_metodo_pagamento_Credit card (automatic)  7043 non-null   bool
 17  conta_metodo_pagamento_Electronic check         7043 non-null   bool
 18  conta_metodo_pagamento_Mailed check             7043 non-null   bool
 19  internet_streaming_tv_1                         7043 non-null   bool
 20  internet_streaming_filmes_1                     7043 non-null   bool
 21  cliente_genero_Masculino                        7043 non-null   bool
dtypes: bool(20), float64(1), int64(1)
memory usage: 247.7 KB

In [49]:
dados_encoded.isnull().sum()

cliente_tenure                                     0
conta_total                                       11
Churn_1                                            0
cliente_senior_1                                   0
cliente_parceiro_1                                 0
cliente_dependentes_1                              0
telefone_servico_1                                 0
internet_servico_Fiber optic                       0
internet_servico_No                                0
internet_seguranca_online_1                        0
internet_backup_online_1                           0
internet_protecao_dispositivo_1                    0
internet_suporte_tecnico_1                         0
conta_contrato_One year                            0
conta_contrato_Two year                            0
conta_fatura_online_1                              0
conta_metodo_pagamento_Credit card (automatic)     0
conta_metodo_pagamento_Electronic check            0
conta_metodo_pagamento_Mailed check                0
internet_streaming_tv_1                            0
internet_streaming_filmes_1                        0
cliente_genero_Masculino                           0
dtype: int64

In [52]:
dados_encoded = dados_encoded.dropna(axis=1)
dados_encoded.isnull().sum()

cliente_tenure                                    0
Churn_1                                           0
cliente_senior_1                                  0
cliente_parceiro_1                                0
cliente_dependentes_1                             0
telefone_servico_1                                0
internet_servico_Fiber optic                      0
internet_servico_No                               0
internet_seguranca_online_1                       0
internet_backup_online_1                          0
internet_protecao_dispositivo_1                   0
internet_suporte_tecnico_1                        0
conta_contrato_One year                           0
conta_contrato_Two year                           0
conta_fatura_online_1                             0
conta_metodo_pagamento_Credit card (automatic)    0
conta_metodo_pagamento_Electronic check           0
conta_metodo_pagamento_Mailed check               0
internet_streaming_tv_1                           0
internet_streaming_filmes_1                       0
cliente_genero_Masculino                          0
dtype: int64